package YWeatherApp;


/**
* YWeatherApp/YWeatherHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from YWeather.idl
* 13 но€бр€ 2015 г. 16:18:31 MSK
*/

abstract public class YWeatherHelper
{
  private static String  _id = "IDL:YWeatherApp/YWeather:1.0";

  public static void insert (org.omg.CORBA.Any a, YWeatherApp.YWeather that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static YWeatherApp.YWeather extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (YWeatherApp.YWeatherHelper.id (), "YWeather");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static YWeatherApp.YWeather read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_YWeatherStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, YWeatherApp.YWeather value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static YWeatherApp.YWeather narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof YWeatherApp.YWeather)
      return (YWeatherApp.YWeather)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      YWeatherApp._YWeatherStub stub = new YWeatherApp._YWeatherStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static YWeatherApp.YWeather unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof YWeatherApp.YWeather)
      return (YWeatherApp.YWeather)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      YWeatherApp._YWeatherStub stub = new YWeatherApp._YWeatherStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
