package YWeatherApp;


/**
* YWeatherApp/YWeather.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from YWeather.idl
* 13 но€бр€ 2015 г. 16:18:31 MSK
*/

public interface YWeather extends YWeatherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface YWeather
