package YWeatherApp;


/**
* YWeatherApp/YWeatherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from YWeather.idl
* 13 но€бр€ 2015 г. 16:18:31 MSK
*/

public interface YWeatherOperations 
{
  String getStringWeather (int cityID);
  void shutdown ();
} // interface YWeatherOperations
